### ISSUE TITLE
Backfill on GA metrics?

### ISSUE THREAD

**Issue by mhkeller** [newslynx/opportunities#128]
For migrated articles, it seems GA hasn't backfilled the data. Starting date on this one is Oct 14, 2014
![screen shot 2015-09-13 at 23 52 23 pm](https://cloud.githubusercontent.com/assets/498744/9837208/a1fdb312-5a72-11e5-8f1c-318217da1ee4.png)

**Comment by mhkeller** [comment]
Article id is 10

**Comment by abelsonlive** [comment]
You'll have to manually re-run these recipes with a larger date query. The simplest way to do this is to temporarily change the `days` option, run, and then change back.

```
$ newslynx api recipes update id=<ga_recipe_id> days=180 
$ newslynx api recipes cook id=<ga_recipe_id>
$ newslynx api recipes update id=<ga_recipe_id> days=<original days value>
```

**Comment by abelsonlive** [comment]
Obviously you can change the `days` option to whatever you think is fit. The broader point is that this doesn't happen _automatically_.

**Comment by mhkeller** [comment]
I ran the backfill but now the timeseries is coming back as 0s and device facets are coming as null

![screen shot 2015-10-06 at 00 25 56 am](https://cloud.githubusercontent.com/assets/498744/10300117/e9e5aa5e-6bc0-11e5-8203-72508839e528.png)
![screen shot 2015-10-06 at 00 26 38 am](https://cloud.githubusercontent.com/assets/498744/10300118/e9e7fb1a-6bc0-11e5-8089-0e0b3845ccef.png)

**Comment by abelsonlive** [comment]
you're going to need to be more specific. Is this for all articles or just this one? How long did you set the `days` when you backfilled? Were you sure the recipe actually completed or did you not check if it error'd or not?

In addition, it also seems like there _is_ data coming back? The share counts will obviously be null because you can't backfill them. Also, there _can_ be zero's in the timeseries, the following rows you posted suggest:

![screenshot 2015-10-06 11 27 09](https://cloud.githubusercontent.com/assets/1621721/10313383/4cb5d7ba-6c1d-11e5-8936-a0eacedd9ef7.png)

the 7 people who visited this page within this hour entered and exited the site on this page. This means they did not register multiple pageviews in their visit which means GA cannot determine their `time_on_page`, and is thus, zero. (You can read more about how google analytics calculates time here: http://cutroni.com/blog/2012/02/29/understanding-google-analytics-time-calculations/)

![screenshot 2015-10-06 11 31 24](https://cloud.githubusercontent.com/assets/1621721/10313478/ceb7ed7a-6c1d-11e5-938d-dcb66038b600.png)

the 14 people who visited this page within this hour all initially entered the site through this page (`ga_entrances` is also 14). This means that the percent of traffic that came to this page in this hour from "internal" pages would reasonably be 0.

I'll dig into this, but i need a bit more information to properly work on these issues.

**Comment by mhkeller** [comment]
This is for all articles. Days was set to `180` and I waited until the recipe went back from `running` to `stable`. 

Looking at it now it seems that the data is correct after having re-run as a part of normal scheduling so I'm not sure why it wouldn't load properly after running via `cook`. adding `keep-an-eye-on`

Some of the articles on ww go back 405 days, if we want to capture timeseries data since then, do you foresee a problem with that must of a timespan?

**Comment by abelsonlive** [comment]
Google analytics doesn't allow you to go back more than 365 days. We could try to run the query though, no reason why it wouldn't work besides a timeout error.

**Comment by abelsonlive** [comment]
Did you refresh the summary metrics after running the backfill?
